# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'IQKeyboardManagerSwift'
    pod 'PopupDialog', '~> 0.7'
    pod 'KWDrawerController', '~> 4.1.6'


end
