# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Goheavy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire'
    pod 'GoogleMaps'
    pod 'GooglePlaces'

  target 'GoheavyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoheavyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
